# Generated by Django 4.0.4 on 2022-05-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_management', '0001_initial'),
        ('table_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('discount', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('items', models.ManyToManyField(to='menu_management.items')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_management.table')),
            ],
        ),
    ]
